# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa75d4f5fade278d7bf05ac11acbf21111b39140d0657e53494b41c16d942ad0493a1d27e035d050049e490f1ba04d68ca78152d26aa3a67d7abc75e60e0dbb

test:
  secret_key_base: e1f31318720abc9d1785f44f37be8cc2711708de3ac205712bdbbfb68b7d6e1339691d34ae7f16c77f5128a04e815a036d536a7f8308cf2afc0917aea51b2e7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
